package com.engram.scheduler;

import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

import static org.junit.jupiter.api.Assertions.*;

/**
 * FSRS-6 correctness tests.
 *
 * Oracle: py-fsrs 6.3.1 (https://github.com/open-spaced-repetition/py-fsrs, tag v6.3.1)
 * Vectors generated by calling Scheduler formula methods directly (Review-state math only).
 * Tolerance: 1e-6 (double precision; py-fsrs uses Python floats, same IEEE 754 doubles).
 */
class FsrsTest {

    private static final double TOL = 1e-6;
    private static final Instant T0 = Instant.parse("2024-01-01T00:00:00Z");

    private final Fsrs fsrs = new Fsrs();

    // ── version() ────────────────────────────────────────────────────────────

    @Test
    void version_returnsExpectedString() {
        assertEquals("FSRS-6", fsrs.version());
    }

    // ── Oracle: initial stability — py-fsrs 6.3.1 ───────────────────────────
    // Vectors: fsrs._initial_stability(Rating(r)) for r in 1..4

    @Test
    void initialStability_oracleMatch() {
        assertEquals(0.212,   fsrs.initialStability(1), TOL); // Again
        assertEquals(1.2931,  fsrs.initialStability(2), TOL); // Hard
        assertEquals(2.3065,  fsrs.initialStability(3), TOL); // Good
        assertEquals(8.2956,  fsrs.initialStability(4), TOL); // Easy
    }

    // ── Oracle: initial difficulty — py-fsrs 6.3.1 ──────────────────────────
    // Vectors: fsrs._initial_difficulty(Rating(r), clamp=True)

    @Test
    void initialDifficulty_oracleMatch() {
        assertEquals(6.4133000000, clampD(fsrs.initialDifficulty(1)), TOL); // Again
        assertEquals(5.1121707056, clampD(fsrs.initialDifficulty(2)), TOL); // Hard
        assertEquals(2.1181039705, clampD(fsrs.initialDifficulty(3)), TOL); // Good
        assertEquals(1.0000000000, clampD(fsrs.initialDifficulty(4)), TOL); // Easy (clamped at 1.0)
    }

    // ── Oracle: retrievability — py-fsrs 6.3.1 ──────────────────────────────
    // Formula: (1 + FACTOR * t / S) ^ DECAY; FACTOR=0.9803464944134797, DECAY=-0.1542

    @Test
    void retrievability_oracleMatch() {
        assertEquals(1.0000000000, fsrs.retrievabilityFormula(0,  1.0),  TOL);
        assertEquals(0.9000000000, fsrs.retrievabilityFormula(1,  1.0),  TOL); // R=0.9 at t=S by definition
        assertEquals(1.0000000000, fsrs.retrievabilityFormula(0,  5.0),  TOL);
        assertEquals(0.9000000000, fsrs.retrievabilityFormula(5,  5.0),  TOL);
        assertEquals(0.8458846451, fsrs.retrievabilityFormula(10, 5.0),  TOL);
        assertEquals(1.0000000000, fsrs.retrievabilityFormula(0,  10.0), TOL);
        assertEquals(0.9000000000, fsrs.retrievabilityFormula(10, 10.0), TOL);
        assertEquals(0.8458846451, fsrs.retrievabilityFormula(20, 10.0), TOL);
        assertEquals(0.9000000000, fsrs.retrievabilityFormula(30, 30.0), TOL);
    }

    // ── Oracle: next difficulty — py-fsrs 6.3.1 ─────────────────────────────
    // base_D = initial_difficulty(Good) = 2.1181039705
    // Vectors: fsrs._next_difficulty(difficulty=base_D, rating=Rating(r))

    @Test
    void nextDifficulty_oracleMatch() {
        double baseD = 2.1181039705;
        assertEquals(7.3945027413, clampD(fsrs.nextDifficulty(baseD, 1)), TOL); // Again
        assertEquals(4.7528584885, clampD(fsrs.nextDifficulty(baseD, 2)), TOL); // Hard
        assertEquals(2.1112142358, clampD(fsrs.nextDifficulty(baseD, 3)), TOL); // Good
        assertEquals(1.0000000000, clampD(fsrs.nextDifficulty(baseD, 4)), TOL); // Easy
    }

    // ── Oracle: next recall stability — py-fsrs 6.3.1 ───────────────────────
    // base_S = initial_stability(Good) = 2.3065, base_D = initial_difficulty(Good) = 2.1181039705
    // Vectors: elapsed in {1d, 5d, 10d} × rating in {Hard, Good, Easy}

    @Test
    void nextRecallStability_oracleMatch() {
        double baseS = 2.3065;
        double baseD = 2.1181039705;

        // elapsed=1d
        double r1 = fsrs.retrievabilityFormula(1, baseS);
        assertEquals(5.3187927675,  fsrs.nextRecallStability(baseD, baseS, r1, 2), TOL); // Hard
        assertEquals(7.3153007441,  fsrs.nextRecallStability(baseD, baseS, r1, 3), TOL); // Good
        assertEquals(11.6874829136, fsrs.nextRecallStability(baseD, baseS, r1, 4), TOL); // Easy

        // elapsed=5d
        double r5 = fsrs.retrievabilityFormula(5, baseS);
        assertEquals(11.8455160314, fsrs.nextRecallStability(baseD, baseS, r5, 2), TOL); // Hard
        assertEquals(18.1678502351, fsrs.nextRecallStability(baseD, baseS, r5, 3), TOL); // Good
        assertEquals(32.0132228553, fsrs.nextRecallStability(baseD, baseS, r5, 4), TOL); // Easy

        // elapsed=10d
        double r10 = fsrs.retrievabilityFormula(10, baseS);
        assertEquals(25.1087201683, fsrs.nextRecallStability(baseD, baseS, r10, 3), TOL); // Good
    }

    // ── Oracle: next forget stability — py-fsrs 6.3.1 ───────────────────────
    // Same base state; rating=Again (1)

    @Test
    void nextForgetStability_oracleMatch() {
        double baseS = 2.3065;
        double baseD = 2.1181039705;

        double r1  = fsrs.retrievabilityFormula(1,  baseS);
        double r5  = fsrs.retrievabilityFormula(5,  baseS);
        double r10 = fsrs.retrievabilityFormula(10, baseS);

        assertEquals(0.5712991793, fsrs.nextForgetStability(baseD, baseS, r1),  TOL);
        assertEquals(0.6825982500, fsrs.nextForgetStability(baseD, baseS, r5),  TOL);
        assertEquals(0.7591601630, fsrs.nextForgetStability(baseD, baseS, r10), TOL);
    }

    // ── First review: review(null, rating, t) via public interface ───────────

    @Test
    void firstReview_nullPrior_allRatings() {
        for (int rating = 1; rating <= 4; rating++) {
            FsrsState state = fsrs.review(null, rating, T0);
            assertNotNull(state);
            assertTrue(state.stability() > 0,   "stability must be positive, rating=" + rating);
            assertTrue(state.difficulty() >= 1.0, "difficulty must be >= 1, rating=" + rating);
            assertTrue(state.difficulty() <= 10.0, "difficulty must be <= 10, rating=" + rating);
            assertEquals(T0, state.lastReviewedAt());
        }

        // Order: higher rating → higher initial stability (Again < Hard < Good < Easy)
        double sAgain = fsrs.review(null, 1, T0).stability();
        double sHard  = fsrs.review(null, 2, T0).stability();
        double sGood  = fsrs.review(null, 3, T0).stability();
        double sEasy  = fsrs.review(null, 4, T0).stability();
        assertTrue(sAgain < sHard, "Again stability must be < Hard");
        assertTrue(sHard  < sGood, "Hard stability must be < Good");
        assertTrue(sGood  < sEasy, "Good stability must be < Easy");
    }

    // ── retrievability(): bounds and monotonicity ────────────────────────────

    @Test
    void retrievability_atReviewInstant_approachesOne() {
        FsrsState state = fsrs.review(null, 3, T0); // Good
        double r = fsrs.retrievability(state, T0);
        assertEquals(1.0, r, TOL, "retrievability at review instant must be 1.0");
    }

    @Test
    void retrievability_decreasesOverTime() {
        FsrsState state = fsrs.review(null, 3, T0);
        double r1  = fsrs.retrievability(state, T0.plus(1,  ChronoUnit.DAYS));
        double r7  = fsrs.retrievability(state, T0.plus(7,  ChronoUnit.DAYS));
        double r30 = fsrs.retrievability(state, T0.plus(30, ChronoUnit.DAYS));
        assertTrue(r1 > r7,  "retrievability must decrease over time (1d > 7d)");
        assertTrue(r7 > r30, "retrievability must decrease over time (7d > 30d)");
    }

    @Test
    void retrievability_alwaysInUnitInterval() {
        FsrsState state = fsrs.review(null, 3, T0);
        for (int days : new int[]{0, 1, 7, 30, 365}) {
            double r = fsrs.retrievability(state, T0.plus(days, ChronoUnit.DAYS));
            assertTrue(r >= 0.0 && r <= 1.0,
                    "retrievability must be in [0,1] at " + days + "d, got " + r);
        }
    }

    @Test
    void retrievability_nullOrUnreviewedState_returnsZero() {
        assertEquals(0.0, fsrs.retrievability(null, T0));
        FsrsState noReview = new FsrsState(5.0, 3.0, null);
        assertEquals(0.0, fsrs.retrievability(noReview, T0));
    }

    // ── Better rating → more durable memory (restoration principle) ──────────

    @Test
    void higherRating_yieldsHigherStabilityFromSamePrior() {
        FsrsState base = fsrs.review(null, 3, T0); // Good first review
        Instant t1 = T0.plus(5, ChronoUnit.DAYS);

        double sAgain = fsrs.review(base, 1, t1).stability();
        double sHard  = fsrs.review(base, 2, t1).stability();
        double sGood  = fsrs.review(base, 3, t1).stability();
        double sEasy  = fsrs.review(base, 4, t1).stability();

        assertTrue(sAgain < sHard, "Again must yield lower stability than Hard");
        assertTrue(sHard  < sGood, "Hard must yield lower stability than Good");
        assertTrue(sGood  < sEasy, "Good must yield lower stability than Easy");
    }

    // ── review() produces valid state ────────────────────────────────────────

    @Test
    void review_invalidRating_throws() {
        assertThrows(IllegalArgumentException.class, () -> fsrs.review(null, 0, T0));
        assertThrows(IllegalArgumentException.class, () -> fsrs.review(null, 5, T0));
    }

    @Test
    void review_subsequentReview_recordsCorrectTimestamp() {
        FsrsState s0 = fsrs.review(null, 3, T0);
        Instant t1 = T0.plus(10, ChronoUnit.DAYS);
        FsrsState s1 = fsrs.review(s0, 3, t1);
        assertEquals(t1, s1.lastReviewedAt());
    }

    // ── Helper: apply same difficulty clamping as Fsrs ───────────────────────

    private static double clampD(double d) {
        return Math.max(1.0, Math.min(10.0, d));
    }
}