spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/engram
    username: engram
    password: engram
  flyway:
    enabled: true
  main:
    banner-mode: "off"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: WARN
    com.engram: INFO
