/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/review/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["next"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SubmitRequest: {
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            conceptId?: string;
            /** Format: int32 */
            rating?: number;
            clientEventId?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        ReviewResultResponse: {
            /** Format: double */
            retrievabilityNow?: number;
            /** Format: date-time */
            dueAt?: string;
            lifecycleState?: string;
        };
        ClozeCardResponse: {
            conceptId?: string;
            prompt?: string;
            answer?: string;
        };
        ConceptView: {
            title?: string;
            lifecycleState?: string;
            /** Format: double */
            retrievability?: number;
            /** @enum {string} */
            moodTier?: "THRIVING" | "HEALTHY" | "FADING" | "WILTING" | "DORMANT";
        };
        DashboardView: {
            /** @enum {string} */
            mode?: "COLD_START" | "STEADY_STATE";
            /** Format: double */
            livingKnowledgePct?: number;
            /** Format: int32 */
            seededCount?: number;
            /** Format: int32 */
            retrievableCount?: number;
            /** Format: int32 */
            frontierCount?: number;
            gardens?: components["schemas"]["GardenView"][];
        };
        GardenView: {
            topicTag?: string;
            /** Format: int32 */
            totalCount?: number;
            /** Format: int32 */
            seededCount?: number;
            /** Format: int32 */
            frontierCount?: number;
            /** Format: double */
            avgRetrievability?: number;
            /** @enum {string} */
            rolledUpTier?: "THRIVING" | "HEALTHY" | "FADING" | "WILTING" | "DORMANT";
            concepts?: components["schemas"]["ConceptView"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewResultResponse"];
                };
            };
        };
    };
    next: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClozeCardResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardView"];
                };
            };
        };
    };
}
